### ISSUE TITLE
Logo and Artwork

### ISSUE THREAD

**Issue by bnavigator** [Free-GPGMail/Free-GPGMail#11]
GPGTools asked me to remove their Logo and Artwork from our fork. This is not a legal requirement, because they publish it in their GPL's source code and don't exclude the resources from the license. However we could be nice and replace the Logo with our own.

Any contributions should be done with an open license, e.g. CreativeCommons.

**Comment by bnavigator** [comment]
Well after I realized, that the current Logo is just a combination of the Apple Mail.app icon combined with a variation of the GnuPG icon, I have only little motivation to comply with GPGTools' request. :facepalm:

**Comment by jemjensen** [comment]
In case you are still interested in doing this, I made up a quick logo that can be swapped in if you like it. I've released it under CC0 so feel free to do anything you like with it. The file should contain both the SVG vector and rasterized versions in the sizes currently used.

https://drive.google.com/file/d/18jxgEtn1DuGMahtuG50yAt77UOGn8rEI/view?usp=sharing

**Comment by bnavigator** [comment]
Thank you! If I ever come around to release a new version, I will include it!
