### ISSUE TITLE
Incompatible with Smallcubed suite of Mail plugins

### ISSUE THREAD

**Issue by odysseus90210** [Free-GPGMail/Free-GPGMail#12]
Even the latest version ( https://github.com/Free-GPGMail/Free-GPGMail/releases/download/2020.2b1/Free-GPGMail_5.mailbundle-2020.2beta1.zip) crashes Mail every time if the Smallcubed white of Mail plugs is also enabled:

https://smallcubed.com/support/downloads.html

**Comment by bnavigator** [comment]
Do you have debug logs, or a crash report file?

https://gpgtools.tenderapp.com/kb/faq/how-can-i-generate-debugging-information#general-debug-information

Is this only happening with Free-GPGMail or also with the commercial GPG Suite?

Did you try to contact Smallcubed's support?

**Comment by odysseus90210** [comment]
I do have crash logs.
This is only happening with Free-GPGMail and not with the commercial GPG Suite. Because of this, I haven't contacted SmallCubed's support -- because I figure they would send me back to you.
[logs.zip](https://github.com/Free-GPGMail/Free-GPGMail/files/6097602/logs.zip)

**Comment by bnavigator** [comment]
Thank you. Unfortunatly I don't see anything (Free-)GPGMail specific in the crashlogs. Can you please at least try to contact @smallcubed? You are paying for their software and they certainly know the Mail.app internals better. They might at least give a hint when they send you back here ;)

**Comment by bnavigator** [comment]
No response in a year
