### ISSUE TITLE
Broken in Big Sur 11.2.3?

### ISSUE THREAD

**Issue by banjopotato** [Free-GPGMail/Free-GPGMail#13]
Since upgrading to Big Sur 11.2.3, I'm getting consistent crashes of Mail when sending signed messages with Free-GPGMail_5.mailbundle.

[Mail_2021-03-10-150245.txt](https://github.com/Free-GPGMail/Free-GPGMail/files/6116802/Mail_2021-03-10-150245.txt)

**Comment by bnavigator** [comment]
Hello, thanks for the report.

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSRegularExpression enumerateMatchesInString:options:range:usingBlock:]: nil argument'
terminating with uncaught exception of type NSException
abort() called

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff2070c6af __exceptionPreprocess + 242
1   libobjc.A.dylib                     0x00007fff204443c9 objc_exception_throw + 48
2   Foundation                          0x00007fff214197aa -[NSRegularExpression numberOfCaptureGroups] + 0
3   GPGMail                             0x0000000114e5905a GPGMail + 221274
4   GPGMail                             0x0000000114e58af4 GPGMail + 219892
```

There is a problem with an empty result of a regular expression search, but from the crashlog it is unclear to me which code portion and used (missing) values cause the crash.

Can you please see if you can create more debugging information? https://gpgtools.tenderapp.com/kb/faq/how-can-i-generate-debugging-information

Does it make a difference, if you send rich formatted emails (MIME multiparts) or plain text?

**Comment by banjopotato** [comment]
I'm not sure what's changed, but it seems that Mail is now working. So: false alarm. Sorry about that.
