### ISSUE TITLE
Immediate crash on Big Sur 11.2.2

### ISSUE THREAD

**Issue by jajcayn** [Free-GPGMail/Free-GPGMail#14]
Hello,

I have M1 Pro machine with Big Sur 11.2.2. I tried to install the latest release (https://github.com/Free-GPGMail/Free-GPGMail/releases/tag/2020.2b1). At first, I did everything as in the README, that is manually sign the bundle with
```
sudo spctl --add ~/Library/Mail/Bundles/Free-GPGMail_5.mailbundle
```
but then the Mail.app was giving me the incompatibility error.

Then I tried the trick with disabling the gatekeeper completely (as mentioned here> https://github.com/Free-GPGMail/Free-GPGMail/issues/7#issuecomment-732293174). After I do this, my Mail.app crashes every time though.

I am attaching the log here> 
[Mail_2021-03-24-230329_NB403160.crash.txt](https://github.com/Free-GPGMail/Free-GPGMail/files/6200741/Mail_2021-03-24-230329_NB403160.crash.txt)

Before I was using the "original" GPGMail 2020.2, which was working perfectly fine.

Thanks for looking into that!

**Comment by cryptoluks** [comment]
Same on 11.3.1.

**Comment by nitz** [comment]
Running into this as well on `11.5.3`. Built my own copy of `GPGMail_5.mailbundle` from the original `2021.1` source and modified it similar to how `2020.2` is here, and ran into the same issues, down to the same call stack in the SIGTRAP. I am running on an M1 Mac, not sure if that's got something to do with it.

**Comment by espositoandrea** [comment]
I'll add a +1 to this issue as it is still occurring on an M1 SoC running Big Sur 11.6. I'm attaching the crash log.
[CrashLog-Mail.txt](https://github.com/Free-GPGMail/Free-GPGMail/files/7373916/CrashLog-Mail.txt)

**Comment by oscrx** [comment]
Same problem here

**Comment by bnavigator** [comment]
Please try the mailbundles with GPGMail 5.1 from https://github.com/Free-GPGMail/Free-GPGMail/pull/19#issuecomment-922470252 and report back.

**Comment by jajcayn** [comment]
hey @bnavigator,
just tried the GPGMail 5.1 from your comment, however, I am getting Incompatible plugin error; macOS 11.6
<img width="259" alt="Screenshot 2021-10-19 at 16 54 08" src="https://user-images.githubusercontent.com/6525217/137936153-7cad92d5-f7c5-4142-85c3-e63d137bff9f.png">

I meant nothing changes, i.e. incompatibility error, when I disable gatekeeper, Mail crashes immediately.

**Comment by bnavigator** [comment]
What does `defaults read /Applications/Mail.app/Contents/Info.plist PluginCompatibilityUUID` say?

**Comment by oscrx** [comment]
I got the same error as @jajcayn after trying the mailbundle from you comment.
When i turn of gatekeeper with ```sudo spctl --master-disable``` mail crashes.

The output of the command you requested: 
```
oscar@oscar-m1 ~ % defaults read /Applications/Mail.app/Contents/Info.plist PluginCompatibilityUUID
2021-10-19 17:09:05.309 defaults[93828:2467816] 
The domain/default pair of (/Applications/Mail.app/Contents/Info.plist, PluginCompatibilityUUID) does not exist
oscar@oscar-m1 ~ % 
```

**Comment by bnavigator** [comment]
The release notes from 5.1 say, it should be compatible with Big Sur on Apple Silicon. The new crashlog should be different from the 5.0 ones using libRosetta.

> When i turn of gatekeeper with sudo spctl --master-disable mail crashes.

So ` sudo spctl --add ~/Library/Mail/Bundles/Free-GPGMail_5.mailbundle` from the README is not sufficient?

**Comment by espositoandrea** [comment]
I've personally tried the latest release downloaded from the GPGSuite official website and everything works. As soon as I download any of the latest two versions from the release page (meaning [this](https://github.com/Free-GPGMail/Free-GPGMail/releases/tag/2020.2b1) or [this](https://github.com/Free-GPGMail/Free-GPGMail/releases/tag/v2020.1b)) or from the [comment](https://github.com/Free-GPGMail/Free-GPGMail/issues/14#issuecomment-946799616) above, Mail will simply crash without any sort of error dialog, except for the crash log that I've uploaded some [here](https://github.com/Free-GPGMail/Free-GPGMail/issues/14#issuecomment-946753462). Just for completeness, I've run the `spctl --add` command, and I've also tried entirely disabling the gatekeeper but nothing changes.

**Comment by jajcayn** [comment]
For me, the same story as @espositoandrea, i.e. official GPGSuite works (the trial period), but none of the FreeGPG bundles: without disabling the master gatekeepers, I am getting incompatibility errors, with disabling the gatekeeper, Mail immediately crashes.

**Comment by bnavigator** [comment]
> except for the crash log that I've uploaded some here.

Thank you for your feedback. However, that crashlog shows `org.gpgtools.gpgmail5 (5.0 - 183859.89)`. The new 2021.1 build should show 5.1.

**Comment by espositoandrea** [comment]
@bnavigator You're right, I'm sorry but with all the versions I've tried I got it mixed up. Here is the crash log from the version in your comment: [Crash GPGTools 5.1 Comment.txt](https://github.com/Free-GPGMail/Free-GPGMail/files/7375083/Crash.GPGTools.5.1.Comment.txt), i.e. `org.gpgtools.gpgmail5 (5.1 - 190380.98)`.

**Comment by bnavigator** [comment]
Okay thank you. After all it is the same crash. Unfortunately I am currently not able to debug this. Any hints welcome.

**Comment by espositoandrea** [comment]
I don't know if this may help, but if I try building the `master` branch on the M1, `make GPGMail_5` outputs a "BUILD FAILED" error message. Sadly I know neither this codebase nor the Objective-C language so it's pretty hard for me to understand what's the reason behind the failure. It seems to be something related to the file `GMSupportPlanAssistantWindow.xib`, but I'm attaching the output of the `make` command for whoever is more experienced than me. [makefile-output.txt](https://github.com/Free-GPGMail/Free-GPGMail/files/7375335/makefile-output.txt)

The strange behavior is that if I just ignore this error and rerun `make GPGMail_5` it just skips the above error completing the build. In this case, the final `.mailbundle` file won't make Mail crash as the one I downloaded, but it outputs an error equal to the one presented [in a comment above](https://github.com/Free-GPGMail/Free-GPGMail/issues/14#issuecomment-946808619).

I hope that this description may help in finding a solution!

**Comment by bnavigator** [comment]
Hi, I just published signed and notarized mailbundles for Free-GPGMail_5 and Free-GPGMail_6 from the v2021.2 sourcecode. Could you please test if these work on your M1's?

**Comment by espositoandrea** [comment]
Hi! I've just tested the file `Free-GPGMail_6.mailbundle` and it works as expected on my M1 using Monterey! Thank you so much for the hard work!
