### ISSUE TITLE
Mail app crashing when sending email with an empty email body

### ISSUE THREAD

**Issue by squazissm** [Free-GPGMail/Free-GPGMail#15]
After adding the free mailbundle plugin I noticed during testing that the apple mail client crashes after sending an email with an empty email body. Seems to be a minor issue ofcourse, but might be good to have a look at.

This is happening on both Catalina & Big sur using the latest version of the free mailbundle plugin & gpgsuite 2020.2

**Comment by bnavigator** [comment]
There is this item in the GPG Suite release notes:

> Sending a signed email with an empty body could lead to a crash [#1079]

Unfortunately the currently relased source code does not include GPG Mail 5.1. Possibly a violation of the GPL.
