### ISSUE TITLE
Cannot set default encryption method to S/MIME

### ISSUE THREAD

**Issue by carlosfamilia** [Free-GPGMail/Free-GPGMail#16]
I tried to set default encryption method with:

```
>defaults write org.gpgtools.gpgmail DefaultSecurityMethod -int 2
```

But it didn't worked, GPG is still selected as default even though:

```
> defaults read org.gpgtools.gpgmail DefaultSecurityMethod
2
```

How can this be solved?

**Comment by carlosfamilia** [comment]
This is still an issue, any news on this?

**Comment by bnavigator** [comment]
Unfortunately not.

I guess you got the commands from the very outdated documentation in the sources. Please note that the domain of the plugin changed to org.free-gpgmail.gpgmailX, where X is the version, but sometimes the version is missing. So you could retry the command with any of those strings.

**Comment by carlosfamilia** [comment]
bnavigator,

That worked like a charm, though without the version number:

defaults read org.free-gpgmail.gpgmail
{
    DefaultSecurityMethod = 2;
    OptionallyEncryptDrafts = 1;
}

**Comment by bnavigator** [comment]
Good. I see the sources were already adjusted accordingly:

https://github.com/Free-GPGMail/Free-GPGMail/blob/f5d7547f6682fdf1e96849e8617635d5f714d7a9/Source/GPGMail_6/Docs/ADVANCED%20PREFERENCES#L14-L18
