### ISSUE TITLE
GPG Mail 5.1 in GPG Suite 2021.1

### ISSUE THREAD

**Issue by bnavigator** [Free-GPGMail/Free-GPGMail#17]
Binaries for GPG Suite 2021.1 have been released in May 2021. A few (?) days later, they also started to provide a [tarball](https://releases.gpgtools.org/GPG_Suite-2021.1_105.txz), supposedly providing the source code. In violation of the GPL, this tarball does not include (yet) the sources of GPG Mail 5.1.

Until we have some source code, there is no chance to update Free-GPGMail to 2021.1 including GPG Mail 5.1. :disappointed:

**Comment by lordp1** [comment]
new source uploaded: https://releases.gpgtools.org/GPG_Suite-2021.1_105_v2.txz
