### ISSUE TITLE
Failed to bypass activate and can not encrypt

### ISSUE THREAD

**Issue by gzqx** [Free-GPGMail/Free-GPGMail#18]
## What I have done
- Installed 2020.1
- removed `GPGMailLoader.mailbundle` (found in `/Library/Mail/Bundles`)
- Copied `Free-GPGMail_4.mailbundle` to `~/Library/Mail/Bundles`
## What I get
- <img width="551" alt="Screenshot 2021-07-20 at 22 15 34" src="https://user-images.githubusercontent.com/24262751/126339604-cbf7587b-72d0-44fd-98ef-7062b923a807.png">
- <img width="926" alt="Screenshot 2021-07-20 at 22 16 49" src="https://user-images.githubusercontent.com/24262751/126339815-312e5ede-4237-4e81-9c13-73b502a18778.png">

**Comment by bnavigator** [comment]
The screenshot show that you are still using the commercial plugin. Be sure to follow the full list, including 5 and 6:

https://github.com/Free-GPGMail/Free-GPGMail#installation


Installation
------------

1. Install GPG Suite suite as normal. Make sure you use the correct version.

2. Find the freshly installed `GPGMailLoader.mailbundle` and delete it.
   (Look into `/Library/Mail/Bundles/`,
   `/Library/Application Support/GPGTools/GPGMail` or the user-specific directory
   `~/Library/Mail/Bundles/`)

3. Build or download the modified mailbundle and copy it
   to your user-specific Mail Bundle directory

        mkdir -p ~/Library/Mail/Bundles/
        cp -r Free-GPGMail_5.mailbundle ~/Library/Mail/Bundles/

4. On macOS 11.0 Big Sur and later, add a Gatekeeper rule to allow the custom
   mailbundle

        sudo spctl --add ~/Library/Mail/Bundles/Free-GPGMail_5.mailbundle

5. Restart Mail.app, go to `Preferences -> General -> Manage Plugins`.
   - Enable the Free GPGMail Plugin.

6. Apply and Restart Mail.app.

**Comment by gzqx** [comment]
I believe I have followed them (twice), and the plugin is as follow
<img width="486" alt="Screenshot 2021-07-21 at 13 08 15" src="https://user-images.githubusercontent.com/24262751/126434134-dff366e7-73fe-409f-878a-f2cb069aab9b.png">

**Comment by bnavigator** [comment]
You can try to "Activate".

**Comment by gzqx** [comment]
<img width="546" alt="Screenshot 2021-07-21 at 14 18 26" src="https://user-images.githubusercontent.com/24262751/126440584-b532a204-e14c-4111-aa45-c533e3bbedae.png">

**Comment by bnavigator** [comment]
Start Trial

**Comment by gzqx** [comment]
It is activated now, thanks!
