### ISSUE TITLE
Support for macOS 12 Monterey - Mail 15

### ISSUE THREAD

**Issue by shreyanshp** [Free-GPGMail/Free-GPGMail#21]
On the latest macOS 12 Monterey the plugin is disabled as it does not support Mail 15 🙇 

GPGMail
![image (6)](https://user-images.githubusercontent.com/21307950/138982875-cae87841-60ef-4535-94de-0785d59599f4.png)
_5

**Comment by Blue-Sailing** [comment]
Is there a timeline for this?

**Comment by bnavigator** [comment]
GPG Tools released 2021.2 and says they are compatible with Monterey. As usual, there is no published source yet.

I am going to try to add the compatible UUID to the existing source on the weekend and you could test if that is enough. But I am afraid that even then, the Gatekeeper problems will persist for a little longer.

**Comment by Scryb** [comment]
I added the UUIDs, re-signed the bundle, did the spctl mojo and the plugin loads, but unfortunately Mail can't create new emails while the plugin is activated, nor replies or forwards. I don't have any experience developing plugins so no idea how to try to debug.

**Comment by bnavigator** [comment]
https://gpgtools.tenderapp.com/discussions/problems/112365-gpg-mail-5-source-code

**Comment by cheemeng** [comment]
The source code has been released https://releases.gpgtools.org/GPG_Suite-2021.2.txz

**Comment by Timvrakas** [comment]
Thanks! Builds cleanly for me!

**Comment by bnavigator** [comment]
Hi, could you please test the freed version in #23?

**Comment by jintakhan** [comment]
Builds quick and clean, working fine with send and receive so far after a straight upgrade from version 5 during cursory testing.

> Hi, could you please test the freed version in #23?

**Comment by Scryb** [comment]
> Hi, could you please test the freed version in #23?

Can also confirm it's working. Finally I can send my emails with signatures the recipients won't notice or care about again 🙃

**Comment by bnavigator** [comment]
Thanks. Published as 2021.2.
