### ISSUE TITLE
Attached signature misidentified as "encrypted attachment," decryption fails

### ISSUE THREAD

**Issue by ewa** [Free-GPGMail/Free-GPGMail#22]
This is with Free-GPGMail_5.mailbundle-2020.2beta1.zip, GPGSuite 2020.2

Here's the offending ["raw" e-mail](https://github.com/Free-GPGMail/Free-GPGMail/files/7610969/signature_test_msg.txt).

Some potentially-relevant screenshots (sorry, I don't know if there's more-developer-friendly log file):
<img width="611" alt="Screen Shot 2021-11-26 at 5 40 11 PM" src="https://user-images.githubusercontent.com/288020/143662806-9f4901a1-3ee6-4100-9c80-fcc8b756ee2d.png">
<img width="490" alt="Screen Shot 2021-11-26 at 5 38 14 PM" src="https://user-images.githubusercontent.com/288020/143662808-1f07383b-986c-4ebc-ba0a-8e90671df13e.png">
<img width="625" alt="Screen Shot 2021-11-26 at 5 37 29 PM" src="https://user-images.githubusercontent.com/288020/143662809-b94b77dd-d5d8-4540-8d86-2ce5f27dda3d.png">
<img width="427" alt="Screen Shot 2021-11-26 at 5 33 01 PM" src="https://user-images.githubusercontent.com/288020/143662814-c2f58091-f586-47ff-a00f-8a2474423fc1.png">

**Comment by bnavigator** [comment]
Hmm,

The error message looks like `gpg` itself got a Hangup signal. Could you please test the newly released 2021.2?

**Comment by mhagelstrom** [comment]
I have the same issue and im using the last release.

<img width="282" alt="image" src="https://user-images.githubusercontent.com/8289100/166703638-0dd9ab77-d287-4c7f-81e2-426546198c5f.png">
<img width="616" alt="image" src="https://user-images.githubusercontent.com/8289100/166703840-5deb2414-04c7-49ff-bb95-0a8ec2f5b40a.png">

**Comment by bnavigator** [comment]
Is this a general problem or only with specific e-mails?

**Comment by mhagelstrom** [comment]
All mails. As far as i know, it started a few days ago.

**Comment by bnavigator** [comment]
Are you able to use gpg on the command line for encrypting and decrypting files?

**Comment by mhagelstrom** [comment]
I had a problem with my keys expiration. It seems to be working fine now.

Maybe an improvement on the error management / error message might be a good idea. But definetely not critical. Thanks for your support

**Comment by bnavigator** [comment]
I am not sure if our code modification is responsible for hiding the GPG error message or if it simply not visible during the call. 

I am closing this issue now. But anyone seeing a similar error message, feel free to continue commenting. General advice in this case is to try to call the gpg command in the shell and see if it spits out a meaningful error.
