### ISSUE TITLE
Sp3 crashing Arm Mail 12.1

### ISSUE THREAD

**Issue by nickkilla** [Free-GPGMail/Free-GPGMail#32]
The new Bundle 6sp3 is crashing on 12.1 M1 Max when trying to draft a new email or reply to an existing one. Mail loads fine and decrypts the message with no issue but any action after causes a sigexec crash.

**Comment by nickkilla** [comment]
[report.txt](https://github.com/Free-GPGMail/Free-GPGMail/files/7709407/report.txt)
The new GPGsuite plugin works without issue.

**Comment by bnavigator** [comment]
```
Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'
terminating with uncaught exception of type NSException
abort() called
```

This could be related to #28 where I removed some items of the preferences page pointing to GPG Tools. Maybe I removed an element which has to be there.

How about [Free-GPGMail_6_12.1_issue32.mailbundle.zip](https://github.com/Free-GPGMail/Free-GPGMail/files/7711072/Free-GPGMail_6_12.1_issue32.mailbundle.zip)?

**Comment by alephc1** [comment]
> ```
> Application Specific Information:
> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'
> terminating with uncaught exception of type NSException
> abort() called
> ```
> 
> 
>      
>   
> 
> This could be related to #28 where I removed some items of the preferences page pointing to GPG Tools. Maybe I removed an element which has to be there.
> 
> 
> How about [Free-GPGMail_6_12.1_issue32.mailbundle.zip](https://github.com/Free-GPGMail/Free-GPGMail/files/7711072/Free-GPGMail_6_12.1_issue32.mailbundle.zip)?

this is working for me macOS 12.1 (21C52)

**Comment by bnavigator** [comment]
@alephc1 Thanks for the report. In order to clarify: Do you also see the crash with the p3 mailbundle?

**Comment by alephc1** [comment]
> @alephc1 Thanks for the report. In order to clarify: Do you also see the crash with the p3 mailbundle?

no, i did not see any crash but with the update from macOS 12.0 to 21.1 (21C52) mailbundle_6 did not load due to incompatibility - sorry in-precise feedback

**Comment by bnavigator** [comment]
Version 6.1 released by GPGTools yesterday mentions in their release notes that they fixed a related problem. As always, unless someone finds the reason and fixes it in our code, we have to wait for them to comply with the open source license and release the source code. They seem to think that they can postpone it for a few weeks.

**Comment by nickkilla** [comment]
@bnavigator The 32 bundle above did not fix the problem. Same issue/crash

[report2.txt](https://github.com/Free-GPGMail/Free-GPGMail/files/7714436/report2.txt)

**Comment by bnavigator** [comment]
@nickkilla I don't know if it is worth a try, but here is a build where I have saved the debuginfo as well. It might help if you create another crashlog with it.

- [Free-GPGMail_6_fordebug.mailbundle.zip](https://github.com/Free-GPGMail/Free-GPGMail/files/7715255/Free-GPGMail_6_fordebug.mailbundle.zip)
- [Free-GPGMail_6_fordebug.mailbundle.dSYM.zip](https://github.com/Free-GPGMail/Free-GPGMail/files/7715260/Free-GPGMail_6_fordebug.mailbundle.dSYM.zip) (you don't need this, just posting for reference)


Otherwise we will just have to wait for an opensourced 6.1. From the release notes:

> Fixes a problem on macOS 12.1 where Mail would crash when composing a new message [#1104] [#1107]

**Comment by nickkilla** [comment]
[3.txt](https://github.com/Free-GPGMail/Free-GPGMail/files/7719597/3.txt)
Still crashing. Here is the report using the debug plugin bundle

**Comment by bnavigator** [comment]
Thanks, that helps. The crash is within a function selecting the private key. Do you have configured sender addresses without a valid private key in the GPG Keyring?

**Comment by bnavigator** [comment]
Any luck with

[Free-GPGMail_6_fordebug2.mailbundle.zip](https://github.com/Free-GPGMail/Free-GPGMail/files/7722899/Free-GPGMail_6_fordebug2.mailbundle.zip)
[Free-GPGMail_6_fordebug2.mailbundle.dSYM.zip](https://github.com/Free-GPGMail/Free-GPGMail/files/7722901/Free-GPGMail_6_fordebug2.mailbundle.dSYM.zip)

?

**Comment by nickkilla** [comment]
> Thanks, that helps. The crash is within a function selecting the private key. Do you have configured sender addresses without a valid private key in the GPG Keyring?

I do have multiple emails in the mail app I use. About half of them have private keys that I use gpg with. The other half I do not use gpg. 

It crashes whenever I try to do a reply to either a gpg mail or a normal email (from all accounts--I tried each). The second I hit reply, bye bye mail app :) Will try with the new debug you attached
Edit----
Same issue. New log attached.
[4.txt](https://github.com/Free-GPGMail/Free-GPGMail/files/7722968/4.txt)
.

**Comment by gramels** [comment]
same crash pattern here
several accounts, some o365 exchange w/o gpg

**Comment by bnavigator** [comment]
Unfortunately I don't have the time, nor do I have any experience in Objective-C programming to properly debug and fix this. The crash occurs somewhere here.

https://github.com/Free-GPGMail/Free-GPGMail/blob/c1bdca44db346ab169bd326b716a32b49c52df05/Source/GPGMail_6/Source/GMKeyManager.m#L172-L174

https://github.com/Free-GPGMail/Free-GPGMail/blob/c1bdca44db346ab169bd326b716a32b49c52df05/Source/GPGMail_6/Source/GPGMailBundle.m#L375-L379

From the release notes of GPG Mail 6.1 cited above (https://github.com/Free-GPGMail/Free-GPGMail/issues/32#issuecomment-994120110), it should be fixed there, but we have to wait for the open source code to be released. Unless some other contributor with more experience in Ojective-C can chime in earlier.

**Comment by gramels** [comment]
@bnavigator no problem. Thanks for for your effort liberating this.

**Comment by gramels** [comment]
looks good so far. Thanks for building!
