### ISSUE TITLE
Saving Encrypted Drafts even when Encrypt Drafts disabled

### ISSUE THREAD

**Issue by walterrowe** [Free-GPGMail/Free-GPGMail#35]
I'm getting encrypted drafts saved even though Encrypt Drafts is unchecked.

macOS 12.1 / Free-GPGmail_6.mailbundle 2021.2p3

**Comment by bnavigator** [comment]
Cannot reproduce with Free-GPGMail 6.1 from 2021.3 (#39)

**Comment by walterrowe** [comment]
This appears to be fixed in 6.1 2021.3
