### ISSUE TITLE
GPG-suite 2021.3 update?

### ISSUE THREAD

**Issue by walterrowe** [Free-GPGMail/Free-GPGMail#38]
Has Free-GPGmail been updated with GPG-suite 2021.3 code base?

**Comment by bnavigator** [comment]
No, they still didn't release the source code on the website despite mandated by the open source licenses. You could try to get it by writing a direct inquiry. Given their hostile mails I received a while ago, I have no interest in communicating with them.

**Comment by intra-au** [comment]
anyone has a link for gpg-suite source code? google is not successful at finding it

**Comment by bnavigator** [comment]
2021.2 is mirrored here: https://github.com/Free-GPGMail/Free-GPGMail/releases/download/v2021.2p2/GPG_Suite-2021.2.txz

2021.3 is not released yet in violation of the BSD-3-Clause and GPL-3.0 licenses. As mentioned above, you could ask them directly, they have to release it.

**Comment by walterrowe** [comment]
I have posted a request for the source on their support page.

**Comment by walterrowe** [comment]
The source code link has been posted.
