### ISSUE TITLE
Incompatible Free-GPGMail 2021.3 in Catalina 10.15.7 with Mail 13.4

### ISSUE THREAD

**Issue by niesel** [Free-GPGMail/Free-GPGMail#40]
I updated GPG-Suite to 2021.3 and found Free-GPGMail 2021.3 to be incompatible with Mail 13.4 in Catalina 10.15.7 

![Screenshot 2022-01-27 at 12 38 42](https://user-images.githubusercontent.com/1552352/151356590-55377e44-1c2d-47a7-a406-7c2aac94f9d7.jpg)

> ~# sw_vers -productVersion
>10.15.7
> ~# defaults read /System/Applications/Mail.app/Contents/Info PluginCompatibilityUUID
> 6EEA38FB-1A0B-469B-BB35-4C2E0EEA9053

**Comment by bnavigator** [comment]
This seems to be the same issue as #36. 

All I can say is that Free-GPGMail_5 is marked as compatible with your macOS version and UUID:

https://github.com/Free-GPGMail/Free-GPGMail/blob/0f9d35f8b6b03064c69bfd715d5b109d83300991/Source/GPGMail_5/Resources/Info.plist#L41-L44

Any hints why it is not working are welcome.

For instance, maybe it is the codesignature and notarization. You could try to remove those from the mailbundle because Catalina does not enforce them. (`_CodeSignature` and `CodeResources` from the `Contents` folder)

**Comment by niesel** [comment]
Yes, the UUID is indeed in the Info.plist
I tried removing _CodeSignature and CodeResources, but this didn't help.

Just to add (maybe it gives hints which I can't see): 
- All Free-GPGMail_X.mailbundle versions showed the same Message like in the screenshot from above.
- It made no difference if the Original GPG-Suite GPGMailloader_6.mailbundle was installed or not. (not activated)
- I have no other mail plug-ins
- I'm using a MacBook Pro (Retina, 15-inch, Mid 2014) with Catalina 10.15.7



I have now built Free-GPGMail locally. (tried with both "master" and tag "v2021.3" - outcomes are the same)
- Free-GPGMail_3.mailbundle => builds 
- Free-GPGMail_4.mailbundle => builds and works. :-)
- Free-GPGMail_5.mailbundle => build fails with linker error
- Free-GPGMail_6.mailbundle => builds 

That's the linker error that arises while building Free-GPGMail_5.mailbundle

```
Ld /Users/xxx/src/Free-GPGMail/Source/GPGMail_5/build/GPGMail.build/Release/Free-GPGMail.build/Objects-normal/arm64/Binary/Free-GPGMail normal arm64 (in target 'Free-GPGMail' from project 'GPGMail')
    cd /Users/xxx/src/Free-GPGMail/Source/GPGMail_5
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-macos10.14 -bundle -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -L/Users/xxx/src/Free-GPGMail/Source/GPGMail_5/build/Release -F/Users/xxx/src/Free-GPGMail/Source/GPGMail_5/build/Release -F/Users/xxx/src/Free-GPGMail/Source/GPGMail_5/Frameworks -F/Users/xxx/src/Free-GPGMail/Source/GPGMail_5/Dependencies/Libmacgpg/build/Release -F/Users/xxx/Library/Containers/com.apple.mail/Data/Library/Frameworks -F/Users/xxx/Library/Frameworks -F/Library/Frameworks -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/PrivateFrameworks -filelist /Users/xxx/src/Free-GPGMail/Source/GPGMail_5/build/GPGMail.build/Release/Free-GPGMail.build/Objects-normal/arm64/Free-GPGMail.LinkFileList -Xlinker -rpath -Xlinker /Library/Frameworks -Xlinker -rpath -Xlinker /Users/xxx/Library/Frameworks -Xlinker -rpath -Xlinker /Users/xxx/Library/Containers/com.apple.mail/Data/Library/Frameworks -bundle_loader /System/Applications/Mail.app/Contents/MacOS/Mail -Xlinker -object_path_lto -Xlinker /Users/xxx/src/Free-GPGMail/Source/GPGMail_5/build/GPGMail.build/Release/Free-GPGMail.build/Objects-normal/arm64/Free-GPGMail_lto.o -Xlinker -final_output -Xlinker /Users/xxx/Library/Mail/Bundles/Free-GPGMail.mailbundle/Contents/MacOS/Free-GPGMail -fobjc-arc -fobjc-link-runtime -undefined dynamic_lookup -framework WebKit -weak_framework Libmacgpg -framework Cocoa -framework Security -framework ExceptionHandling -Xlinker -dependency_info -Xlinker /Users/xxx/src/Free-GPGMail/Source/GPGMail_5/build/GPGMail.build/Release/Free-GPGMail.build/Objects-normal/arm64/Free-GPGMail_dependency_info.dat -o /Users/xxx/src/Free-GPGMail/Source/GPGMail_5/build/GPGMail.build/Release/Free-GPGMail.build/Objects-normal/arm64/Binary/Free-GPGMail
ld: warning: directory not found for option '-F/Users/xxx/src/Free-GPGMail/Source/GPGMail_5/Dependencies/Libmacgpg/build/Release'
ld: warning: directory not found for option '-F/Users/xxx/Library/Containers/com.apple.mail/Data/Library/Frameworks'
ld: warning: directory not found for option '-F/Users/xxx/Library/Frameworks'
ld: can't link with a main executable file '/System/Applications/Mail.app/Contents/MacOS/Mail' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld /Users/xxx/src/Free-GPGMail/Source/GPGMail_5/build/GPGMail.build/Release/Free-GPGMail.build/Objects-normal/arm64/Binary/Free-GPGMail normal arm64
(1 failure)
make[1]: *** [Free-GPGMail.mailbundle] Error 65
make: *** [GPGMail_5] Error 2
```

So Free-GPGMail_5 fails linking for architecture arm64, but building Free-GPGMail_6 doesn't fail at this point...
Maybe these infos might help resolve the general isssue. 
If I can provide any additional info let me know.

The problem is resolved for me personally as Free-GPGMail_4.mailbundle works fine now. 


Thanks for your work!

**Comment by bnavigator** [comment]
I can imagine that Catalina cannot build for arm. So you have to remove the arm target from Xcode before building Free-GPGMail_5.

**Comment by bnavigator** [comment]
Instead of manually removing the signatures you could also try to locally resign the existing bundles.

**Comment by niesel** [comment]
> I can imagine that Catalina cannot build for arm. 

That's what I thought. But then what wonders me is that Free-GPGMail_6 did build for arm64. 

> Instead of manually removing the signatures you could also try to locally resign the existing bundles.

I'm fine now as the local build of Free-GPGMail_4 works for me.

**Comment by wherget** [comment]
Encountered this issue just now as well, look to be signature for me (from Console):
```
NSBundle </Users/REDACTED/Library/Containers/com.apple.mail/Data/DataVaults/MailBundles/Users/REDACTED/Library/Mail/Bundles/Free-GPGMail_5.mailbundle> (not yet loaded) failed to load. The error was:
Error Domain=NSCocoaErrorDomain Code=3588 "dlopen(/Users/REDACTED/Library/Containers/com.apple.mail/Data/DataVaults/MailBundles/Users/REDACTED/Library/Mail/Bundles/Free-GPGMail_5.mailbundle/Contents/MacOS/Free-GPGMail, 0x0109): code signature invalid (errno=1) sliceOffset=0x00004000, codeBlobOffset=0x000A54F0, codeBlobSize=0x00005CE0 for '/Users/REDACTED/Library/Containers/com.apple.mail/Data/DataVaults/MailBundles/Users/REDACTED/Library/Mail/Bundles/Free-GPGMail_5.mailbundle/Contents/MacOS/Free-GPGMail'" 
```

Running on
```
Mail Version 13.4 (3608.120.23.2.7)
OS X Version 10.15.7 (19H1715)
```

Tried with both _4 and _5 prebuilt from the releases page (same error for both). Even removing `_CodeSignature` and `CodeResources` did not help. Maybe as of a recent update signatures are enforced? I'll try locally re-signing and if that doesn't help building locally.

Edit: Locally signing with anonymous identity did the trick.
```
codesign --deep --force --verbose --sign "-" Free-GPGMail_5.mailbundle
```

Edit2: Could be a weird interaction with permissions and DataVaults? I'm a bit stumped. Because a freshly extracted zip:
```
$ codesign --verify -v Free-GPGMail_5.mailbundle
Free-GPGMail_5.mailbundle: valid on disk
Free-GPGMail_5.mailbundle: satisfies its Designated Requirement
```

**Comment by bnavigator** [comment]
Please check if [Free-GPGMail_5-2021.3.1-unsigned.mailbundle](https://github.com/Free-GPGMail/Free-GPGMail/releases/tag/v2021.3.1) works for you.

**Comment by wherget** [comment]
Looks to be working out of the box. Thanks!
