### ISSUE TITLE
Homebrew distribution

### ISSUE THREAD

**Issue by EivindArvesen** [Free-GPGMail/Free-GPGMail#41]
Thanks for this projects!

Have you considered distributing this plugin via the package manager [Homebrew](https://brew.sh)?

I think this could have the potential to make setup significantly easier for end users (particularly if GnuPG and Libmacgpg could be installed automatically).

**Comment by jpbernius** [comment]
This could depend on the [`gpg-suite-no-mail`](https://formulae.brew.sh/cask/gpg-suite-no-mail) cask.
So this would include installation of the (required?) installation of GPG suite easily.

**Comment by bnavigator** [comment]
I like the idea. As mentioned before, I do not own a Mac myself and thus have no experience with homebrew, let alone packaging for it. Please feel free to come up with something.

**Comment by jpbernius** [comment]
Do we actually need the GPG Suite, or is `Libmacgpg` enough in combination with the `mailbundle`?

**Comment by bnavigator** [comment]
* The mailbundle shares some settings dialogs with the other programs from the suite, but I don't think you need them installed for it.
* You definitely need GnuPG somehow, but that is already in Homebrew.
* No GPG Keychain means that you have to manage keys with gpg from the command line.

**Comment by EivindArvesen** [comment]
After struggling somewhat with trying to bundle `Libmacgpg` as a Formula for Homebrew, I think depending on the [`gpg-suite-no-mail`-cask](https://formulae.brew.sh/cask/gpg-suite-no-mail), as suggested by @jpbernius, is the way to go.

Additionally, it has the added benefit of also installing GPG Keychain and such, as @bnavigator mentions + avoiding manual versioning (the official repo only denotes current version in a config file).

I've written a Cask that successfully sets everything up; Just need to ensure that post-install output detailing with manual steps in Mail.app etc. are complete, and complies with Homebrew standards.

Not sure where to go from there – possibly push my repo to GitHub so that others can test the cask, before making a PR to [Homebrew Cask](https://github.com/Homebrew/homebrew-cask)?

**Comment by EivindArvesen** [comment]
Cask is live at [this repo](https://github.com/EivindArvesen/Free-GPGMail-Tap).

To install, run `brew install EivindArvesen/Free-GPGMail-Tap/free-gpgmail`.
Please let me know if you have any issues; It ran OK on my machine. 

If I don't hear about any issues, I'll probably get started on getting this into Homebrew's default cask tap. Might also look into auto-publishing new versions, if I have time.

**Comment by EmlJnke** [comment]
It does not work, the GitHub repo of the cask has the wrong adress:

```
==> Tapping eivindarvesen/free-gpgmail-tap
Cloning into '/opt/homebrew/Library/Taps/eivindarvesen/homebrew-free-gpgmail-tap'...
remote: Repository not found.
fatal: repository 'https://github.com/eivindarvesen/homebrew-free-gpgmail-tap/' not found
Error: Failure while executing; `git clone https://github.com/eivindarvesen/homebrew-free-gpgmail-tap /opt/homebrew/Library/Taps/eivindarvesen/homebrew-free-gpgmail-tap --origin=origin --template=` exited with 128.
```

**Comment by EivindArvesen** [comment]
@EmlJnke did you copy-paste the command I wrote in my previous comment?
I don't understand why your output says "https://github.com/eivindarvesen/homebrew-free-gpgmail-tap/" rather than "https://github.com/eivindarvesen/free-gpgmail-tap/".

Running `brew install EivindArvesen/Free-GPGMail-Tap/free-gpgmail` verbatim works fine on my end.

**Comment by wrenchpilot** [comment]
@EivindArvesen there's definitely a naming issue with this cask.  It probably works for you because the directory that it's attempting to install to actually exists.

`brew tap --repair EivindArvesen/Free-GPGMail-Tap/free-gpgmail
fatal: cannot change to '/usr/local/Homebrew/Library/Taps/eivindarvesen/homebrew-free-gpgmail-tap': No such file or directory
Error: Failure while executing; ``git -C /usr/local/Homebrew/Library/Taps/eivindarvesen/homebrew-free-gpgmail-tap fetch origin`` exited with 128.`

`git clone https://github.com/eivindarvesen/free-gpgmail-tap/ /usr/local/Homebrew/Library/Taps/eivindarvesen/homebrew-free-gpgmail-tap`

 `brew install EivindArvesen/Free-GPGMail-Tap/free-gpgmail`  now works.

**Comment by EivindArvesen** [comment]
Sorry about that – there was a repo naming convention I'd missed.
Running `brew install EivindArvesen/Free-GPGMail-Tap/free-gpgmail` should now work without any prerequisites.

Updated the cask to v2021.3.1

**Comment by jpbernius** [comment]
Hey @EivindArvesen, I tested this and can confirm that it works. [I rebased your changes on top of the official repository](https://github.com/jpbernius/homebrew-cask/tree/free-gpgmail). If it is ok for you, I will open a PR to get this merged into the official Cask Repository.

**Comment by EivindArvesen** [comment]
@jpbernius Sorry for the late reply – been sick...
Great work! 
Does the livecheck mean that the cask will be autoupdated, or will every new release need a PR to bump versions in homebrew?
