### ISSUE TITLE
Support for macOS 12 Monterey - Mail 15

### ISSUE THREAD

**Issue by lip-o** [Free-GPGMail/Free-GPGMail#42]
On the latest macOS 12 Monterey the plugin is disabled as it does not support Mail 1
![138982875-cae87841-60ef-4535-94de-0785d59599f4](https://user-images.githubusercontent.com/81316997/156579830-99b485f8-44e9-4948-a90c-f90f4389db31.png)
5

**Comment by lip-o** [comment]
On Big Sur or later, you need to codesign the mailbundle with a developer key
` sudo spctl --add ~/Library/Mail/Bundles/Free-GPGMail_*.mailbundle`

**Comment by bnavigator** [comment]
Version 5 is not compatible with Monterey. Use Version 6.
