### ISSUE TITLE
Incompatible plug-in with Mail 16.0, macOS 12.3, Mail 16.0

### ISSUE THREAD

**Issue by iharsuvorau** [Free-GPGMail/Free-GPGMail#44]
Building from `master`, produces a mailbundle that's in conflict with Mail:

<img width="372" alt="Screenshot 2022-03-09 at 10 39 30" src="https://user-images.githubusercontent.com/6259054/157408612-5c6c3f3a-6b7d-4346-ac6c-0870bd21ea48.png">

macOS: 12.3 Beta 21E5227a
Mail: 16.0 (3696.80.82.1.1)

**Comment by JayBrown** [comment]
New GPGMail needed for that: https://github.com/Free-GPGMail/Free-GPGMail/issues/43

(I don't think that the source code has been released yet.)

**Comment by chrisswanda** [comment]
Same issue with the new Monterey 12.3 release.

System Version:	macOS 12.3 (21E230)
Mail - Version 16.0 (3696.80.82.1.1)

**Comment by rbernardes** [comment]
Same here.
After upgrade to 12.3 the plugin stopped to work.

**Comment by bfabiszewski** [comment]
New UUID is needed in Info.plist. 
Then rebuild or just resign the bundle.
```
    <key>Supported12.3PluginCompatibilityUUIDs</key>
    <array>
        <string>A4B49485-0377-4FAB-8D8E-E3B8018CFC21</string>
    </array> 
```

**Comment by bnavigator** [comment]
I have released [2021.3.1](https://github.com/Free-GPGMail/Free-GPGMail/releases/tag/v2021.3.1) based on the old source code but with the new updated UUID.

**Comment by cgtyoder** [comment]
@bnavigator works great in macOS 12.3 (Mail 16.0) - thanks much!

**Comment by shreyanshp** [comment]
@bnavigator Apologies is there any documentation on how to install this new package, as I cannot find mailbundle inside it?
https://github.com/Free-GPGMail/Free-GPGMail/releases/download/v2021.3.1/Free-GPGMail_6-2021.3.1.mailbundle.zip

**Comment by socialmedialabs** [comment]
2021.3.1 didn't work for me up until I fixed another plugin with these instructions:
https://c-command.com/spamsieve/help/resetting-mail-s-privat

Hope this helps.
