### ISSUE TITLE
Support for macOS 12.4 - Mail 16

### ISSUE THREAD

**Issue by bhuisgen** [Free-GPGMail/Free-GPGMail#51]
Plugin v16 is not allowed on macOS 12.4.

**Comment by rbernardes** [comment]
Same here :(

**Comment by ghost** [comment]
Same here

**Comment by onemanifest** [comment]
Ditto

**Comment by chrisswanda** [comment]
Just like clockwork.

**Comment by revil-O** [comment]
PlugIn was deactivated by mail with the following comment: "Contact the developers of these plug-ins to get versions that are compatible with Mail 16.0."

regards

**Comment by bnavigator** [comment]
If we are lucky, it's just missing the new UUID, same as https://github.com/Free-GPGMail/Free-GPGMail/issues/44#issuecomment-1071182869 for the last release.

I am on the road and don't have access to a mac. Could you please report the new UUID?

```bash
sw_vers -productVersion
```

```bash
defaults read /System/Applications/Mail.app/Contents/Info PluginCompatibilityUUID
```

You might even work around it yourself when you add the UUID to the Info.plist and codesign locally:

```bash
codesign --deep --force --verbose --sign "-" ~/Library/Mail/Bundles/Free-GPGMail_6.mailbundle
```

**Comment by bnavigator** [comment]
Assuming the UUID didn't change but actually are only missing for the new minor version number, I added some entries to the Info.plist. Please test:

[Free-GPGMail_6_2022.1.1.mailbundle.zip](https://github.com/Free-GPGMail/Free-GPGMail/files/8750066/Free-GPGMail_6_2022.1.1.mailbundle.zip)

```xml
	<key>CFBundleVersion</key>
	<string>196266.192</string>
```

**Comment by chrisswanda** [comment]
Worked for me.

**Comment by rbernardes** [comment]
Thank you! Worked for me!

**Comment by onemanifest** [comment]
Great! Works! Thanks for the swift action.

**Comment by revil-O** [comment]
thank you very much for the quick and perfect work !!!!!

**Comment by PhilETaylor** [comment]
I have forked this issue for Ventura beta 9 here https://github.com/Free-GPGMail/Free-GPGMail/issues/59
