### ISSUE TITLE
macOS Ventura support

### ISSUE THREAD

**Issue by nervous-inhuman** [Free-GPGMail/Free-GPGMail#54]
Currently, Free-GPGMail doesn't work with the Mail.app bundled with macOS Ventura 13.0 Beta (22A5295i)

Would it be possible to be able to add support for this version of macOS?

Thank you

**Comment by bnavigator** [comment]
Could you give https://github.com/Free-GPGMail/Free-GPGMail/issues/51#issuecomment-1133945066 a try please?

If the new macOS version changed some API, we might have to wailt for someone to adjust the Free-GPGMail code.

**Comment by bnavigator** [comment]
No response given.
