### ISSUE TITLE
Problems with M1 Mac Pro, Catalina 12.5 and Mail 16.0

### ISSUE THREAD

**Issue by jaroslawsky** [Free-GPGMail/Free-GPGMail#55]
Thanks for your great work,

but unfortunately I get it not working in my new M1 Mac Book Pro.

Compilation had no problem, but Mail does not accept the build bundle.
I tried to add the new UUID to the lists in Info.plist as described in #51. But when I call
codesign --deep --force --verbose --sign "-" ~/Library/Mail/Bundles/Free-GPGMail_6.mailbundle
the result is:
/Users/klaus/Library/Mail/Bundles/Free-GPGMail_6.mailbundle: bundle format unrecognized, invalid, or unsuitable

Is it a problem with the ARM processor or with the newest os or mail app?

Best regards,
Klaus

[Info.plist.zip](https://github.com/Free-GPGMail/Free-GPGMail/files/9252025/Info.plist.zip)

**Comment by jaroslawsky** [comment]
Well,

I made a mistake by adding the UUID to the Info.plist.

Now I used the current master with the UUID already added for Mac OS 12.5. This produces a different error message. Now it's not possible to search for malware inside the plugin. The codesign command results in the same error.

I guess that a correct code signing would solve the problem?

Best regards,
Klaus

<img width="297" alt="Bildschirmfoto 2022-08-03 um 16 11 42" src="https://user-images.githubusercontent.com/24761522/182631931-1267afbf-7864-4ff5-8873-20b45f5c3633.png">
<img width="298" alt="Bildschirmfoto 2022-08-03 um 16 12 32" src="https://user-images.githubusercontent.com/24761522/182631969-4eef6044-223f-466f-840e-4ce0e1215664.png">

**Comment by jaroslawsky** [comment]
The changed gatekeeper behavior on M1 Macs ist the problem. The solution is described here: https://wiki.lazarus.freepascal.org/Code_Signing_for_macOS

After declaring terminal.app as development tool and calling
sudo spctl --master-disable
Mail accepts the Plugin.

A later
sudo spctl --master-enable
does not change this.

Best regards,
Klaus

**Comment by bnavigator** [comment]
Hi Klaus,

thank you for digging into this.

So what's the suggested action here? Update the instructions for self-compiling? Add more UUIDs to the plist? Can you provide them? Please open PRs.

With new UUIDs we could release a patchlevel update.

**Comment by jaroslawsky** [comment]
Hi Ben,

it's not a UUID Problem. The added UUIDs are fine. It's a problem with the changed gatekeeper behavior on M1 Macs. So an instruction update would be nice.

**Comment by bnavigator** [comment]
It is a UUID problem, if they are missing in the binary releases. You don't need to compile yourself and hack gatekeeper if you use the release.

So what are the additional UUIDs?

**Comment by bnavigator** [comment]
What about ad-hoc signing the mailbundle instead of fiddling with gatekeeper?
