### ISSUE TITLE
Libmacpgg was not found

### ISSUE THREAD

**Issue by YusufGuler-Bilgi** [Free-GPGMail/Free-GPGMail#56]
Hi,

Recently had this error.

<img width="394" alt="Ekran Resmi 2022-08-31 23 47 38" src="https://user-images.githubusercontent.com/95856908/187779017-6a03df1b-0701-43d5-babb-701759331450.png">

**Comment by bnavigator** [comment]
From the README:

> Installation
> ------------
>
> 1. Download and install Free-GPGMail:
>    - Using [Homebrew](https://brew.sh):
>      ```bash
>      brew install --cask free-gpgmail
>      ```
>    - or manually:
>        1. **Download and install the GPG Suite .dmg file from the commercial seller or from the
>           [Free-GPGMail releases page](../../releases/).**
