### ISSUE TITLE
GPG Keychain is missing when I install the app

### ISSUE THREAD

**Issue by leighgallagher** [Free-GPGMail/Free-GPGMail#57]
I have just installed free-gpgmail and have been able to add the plugin into Mail fine, but cannot find the GPG keychain app to set up my key. I have tried uninstalling and reinstalling the app, but still can't find it even though GPG suite is in my System Preferences window and appears as a tab in Mail Preferences. 

A colleague of mines has just installed the app and has the keychain, but has the Incompatible Plug-Ins Disabled pop up when they try to install the plugin. Related to [This](https://github.com/Free-GPGMail/Free-GPGMail/issues/55)

I am running Mail 16.0 and Monterey 12.5.1 on a Macbook Pro M1.

**Comment by bnavigator** [comment]
You say, you have GPG suite in your Prferences window, but did you actually install the full GPG suite?
