### ISSUE TITLE
Ventura beta 9

### ISSUE THREAD

**Issue by PhilETaylor** [Free-GPGMail/Free-GPGMail#59]
`sw_vers -productVersion`

```
13.0
```

`defaults read /System/Applications/Mail.app/Contents/Info PluginCompatibilityUUID`

```
890E3F5B-9490-4828-8F3F-B6561E513FCC
```

I have read https://github.com/Free-GPGMail/Free-GPGMail/issues/51#issuecomment-1133945066 and attempted to add the new UUID but with no joy, I dont know how to generate the CFBundleVersion (Im a PHP developer, not a Mac developer :) )

unlike the other Ventura issue #54  Im responsive if you ask me questions to get the info you need :)

**Comment by PhilETaylor** [comment]
Found this in console, so did that... 

```
Plugin compatibility check failed for Free-GPGMail_6.mailbundle. The plugin's Info.plist must have a Supported13.0PluginCompatibilityUUIDs key whose value is an array of strings that contains the compatibility UUIDs for the supported versions of Mail. The compatibility UUID value is found in the PluginCompatibilityUUID key of Mail's Info.plist
```

ok so I got a little further, I added 

```xml
	<key>Supported13.0PluginCompatibilityUUIDs</key>
    <array>
    	<string>890E3F5B-9490-4828-8F3F-B6561E513FCC</string>
    </array>
```

Then rebuilt and relaunched and get 

<img width="309" alt="Screenshot 2022-09-27 at 22 40 44" src="https://user-images.githubusercontent.com/400092/192640972-6a09ed14-a826-4bf1-ad0a-9599305becf3.png">

tried to replace the code signature again but still no joy :) code signing is all new to me :)

**Comment by PhilETaylor** [comment]
ok one more discovery is that in System Preferences -> Privacy & Security -> General 

I now see this after the second popup 

<img width="499" alt="Screenshot 2022-09-27 at 22 43 00" src="https://user-images.githubusercontent.com/400092/192641421-af2a14eb-08df-4329-ac92-8bed7193dccf.png">

But even clicking "Open Anyway" its just ending up in a loop and disabling the plugin on each load.

**Comment by PhilETaylor** [comment]
I bloody love being a developer with a scratch to itch... no idea what I did haha... just kept going around the loop trying to click "open anyway" and "ok" and then finally it loaded the plugin somehow... 

🎉🎉🎉🎉🎉🎉🎉🎉

<img width="923" alt="Screenshot 2022-09-27 at 22 50 03" src="https://user-images.githubusercontent.com/400092/192642187-e46ceaf6-8678-44e3-85ae-dfe7b6a984fe.png">

**Comment by bnavigator** [comment]
Closed by #60. Just need a new release.

**Comment by bnavigator** [comment]
2022.1.2 has been built, signed, notarized and released. No more fiddling with developer warning dialogues necessary, I hope.

**Comment by PhilETaylor** [comment]
The notarized build loaded perfectly thank you. (now to start reporting other bugs haha)
