### ISSUE TITLE
Free-GPGMail_6.mailbundle not compatible with current GPG Suite release (2022.2)

### ISSUE THREAD

**Issue by AwlsomeAlex** [Free-GPGMail/Free-GPGMail#66]
This is what I get when I try to open Mail.app after installing the latest GPG Suite (2022.2) and Free-GPGMail (2022.1.1)
```
Mail has disabled the following plug-ins:
Free-GPGMail_6.mailbundle
Contact the makers of these plug-ins for versions that are compatible with Mail 16.0.
```

**Comment by bnavigator** [comment]
Good to know that GPG suite was released today. We will have to wait for the source code, again.

We used to have a statement that Free-GPGMail 20XX.X only works with GPG Suite 20YY.Y where X == Y.  In other words, don't update before compatibility is ensured. Somehow this statement is lost.

**Comment by bnavigator** [comment]
Clarified requirement in fec469ad464649f112cf178bed9b4e94ffb7d8ae
