### ISSUE TITLE
Support for GPG Mail 7

### ISSUE THREAD

**Issue by fuomag9** [Free-GPGMail/Free-GPGMail#67]
Hi, 

Is there any eta or working guide for GPG Mail 7? As it could improve issues such as #64 and #65

**Comment by PhilETaylor** [comment]
I renewed my subscription to the official GPGMail7 and both #64 and #65 are not a problem with their codebase. 

for £12 it was worth the investment in my personal use case, although I appreciate the reason this project exists also.

**Comment by bnavigator** [comment]
We cannot update before GPGTools fulfills their GPL mandated requirement to publish the source code. They maintain the standpoint that they can delay it for about 4 weeks and nobody challenges them on it.

The only alternative is to write our own Free-GPGMail 7 supporting Ventura. I do not have the resources for it, but whoever wants to fork and work on it is welcome to submit pull request.

**Comment by andatche** [comment]
Source for the 2022.2 release, which includes GPGMail 7, is now available [here](https://releases.gpgtools.org/GPG_Suite-2022.2.txz) at last.

**Comment by bnavigator** [comment]
There is a beta version of Free-GPGMail 7 for testing in #68.

**Comment by bnavigator** [comment]
Merged #68. Reopening until the new release is out

**Comment by bnavigator** [comment]
Free-GPGMail 2022.2 released

**Comment by revil-O** [comment]
excellent work guys ! thank you very much

**Comment by NatHarari** [comment]
I just wanted to add my voice to the accolades of gratitude. Great work and thank you very much. 👍

**Comment by rafaelmaeuer** [comment]
I want to leave a big thank you too!
