### ISSUE TITLE
Free-GPGMail Ventura 13.1 beta2

### ISSUE THREAD

**Issue by Heliophon** [Free-GPGMail/Free-GPGMail#69]
Hi,
first: thanks for your really great work.
I was very happy seeing Free-GPGMail_7 for Ventura but it does not work with the actual 13.1 beta ("... incompatible plug...").
Tried to edit the info.plist with "Supported ... 13.1 UUID" but that does not do the job.
Any suggestions?
Sincerely,
H.

**Comment by bnavigator** [comment]
Do you have a  UUID for 13.1 beta? Which UUID did you try?

See https://github.com/Free-GPGMail/Free-GPGMail/issues/51#issuecomment-1133945066

**Comment by Heliophon** [comment]
It seems to be the same as for 13.0 (look at info.plist in GPGMail 7) (890E3F5B-9490-4828-8F3F-B6561E513FCC)

**Comment by bnavigator** [comment]
You can test this one: 
[Free-GPGMail_7_signed.mailbundle.zip](https://github.com/Free-GPGMail/Free-GPGMail/files/10013323/Free-GPGMail_7_signed.mailbundle.zip)

**Comment by Heliophon** [comment]
Hi Ben,

works like a charm. Thank you very much.

Sincerely,
H.
