### ISSUE TITLE
Can not send 

### ISSUE THREAD

**Issue by Fatpandac** [Free-GPGMail/Free-GPGMail#70]
Can not send an email with Free-GPGMail and get some error.
![SCR-20221114-c67](https://user-images.githubusercontent.com/30423976/201554094-e0c45bbc-557d-4ed2-b22c-5a0ffc7cf8a1.png)

**Comment by PhilETaylor** [comment]
Reboot.

I get this from time to time with GPGMail after not rebooting for months

**Comment by Fatpandac** [comment]
OK, I'll try it late.

**Comment by Fatpandac** [comment]
> Reboot.
> 
> I get this from time to time with GPGMail after not rebooting for months

Yep, it's work, thank you very much.
