### ISSUE TITLE
Ventura 13.1 Issue

### ISSUE THREAD

**Issue by kevinwincott** [Free-GPGMail/Free-GPGMail#73]
Following the latest update for Ventura im getting this:

```
Mail has disabled the following plug-ins:
Free-GPGMail_7.mailbundle
Contact the makers of these plug-ins for versions that are compatible with Mail 16.0.
```

im running Mail 16 too

`Version 16.0 (3731.300.101.1.3)`

**Comment by MohamedElashri** [comment]
I'm getting the same error, This happened after my update to Ventura `13.1 (22C65)` and running `Version 16.0 (3731.300.101.1.3)` and it seems there is no update from `GPG Suite`

**Comment by bnavigator** [comment]
Please report the new UUIDS. See https://github.com/Free-GPGMail/Free-GPGMail/issues/51#issuecomment-1133945066

**Comment by MohamedElashri** [comment]
> Please report the new UUIDS. See [#51 (comment)](https://github.com/Free-GPGMail/Free-GPGMail/issues/51#issuecomment-1133945066)

The UUID did not change, it is still  `890E3F5B-9490-4828-8F3F-B6561E513FCC` and `sw_vers -productVersion` is `13.1`

**Comment by bnavigator** [comment]
https://github.com/Free-GPGMail/Free-GPGMail/blob/3a492de045c27df37aabd61e662017980908af98/Source/GPGMail_7/Resources/Info.plist#L43-L46

Are you sure that you installed Free-GPGMail7 from 2022.2.1?

**Comment by MohamedElashri** [comment]
> https://github.com/Free-GPGMail/Free-GPGMail/blob/3a492de045c27df37aabd61e662017980908af98/Source/GPGMail_7/Resources/Info.plist#L43-L46
> 
> Are you sure that you installed Free-GPGMail7 from 2022.2.1?

Yes, You are right, I did not update the latest version. I was still on the first Ventura compatible version. Problem get fixed by installing the new version.  Sorry about that

**Comment by kevinwincott** [comment]
`890E3F5B-9490-4828-8F3F-B6561E513FCC`

is the correct version? if so, its still failing for me
