### ISSUE TITLE
Libmacgpg not found

### ISSUE THREAD

**Issue by NatHarari** [Free-GPGMail/Free-GPGMail#74]
I'm getting an error when I open Mail after installing Free-GPG via brew which states that Libmacgpg is not found.

I'm on Ventura 16.3, MacBook Pro M1 Max

**Comment by PhilETaylor** [comment]
`Ventura 16.3` ?

Ventura 13.2 is the latest development beta of Ventura..

`16.3` is an iOS version number.

**Comment by NatHarari** [comment]
Oops! I did mean 13.2. Sorry.

**Comment by bnavigator** [comment]
Did brew install gpg-suite-no-mail?

https://github.com/Homebrew/homebrew-cask/blob/331b85f998dec1134c096910b4728cba51e76a74/Casks/free-gpgmail.rb#L43
https://formulae.brew.sh/cask/gpg-suite-no-ma

https://github.com/Free-GPGMail/Free-GPGMail/issues/56#issuecomment-1233458236

**Comment by NatHarari** [comment]
Thanks! That worked. It didn't install as a default though and I didn't see any reference in the installation instructions on the page here:

https://github.com/Free-GPGMail/Free-GPGMail

Maybe somebody can update that?

**Comment by bnavigator** [comment]
It is listed as a requirement in the cask and should have been installed by brew automatically.

**Comment by NatHarari** [comment]
I don't know why it wasn't, but it made all the difference. Thanks.
