### ISSUE TITLE
MacOS Ventura 13.2 - Cannot save to drafts

### ISSUE THREAD

**Issue by jameswillhoite** [Free-GPGMail/Free-GPGMail#75]
Whenever I try and respond to a email I get the following error

<img width="277" alt="image" src="https://user-images.githubusercontent.com/44815350/215169446-05ca381c-5f98-4915-9e8b-4ee0e1043e76.png">

If I completely quit the Mail.app then reopen and respond to the email it goes through with no problem. I'm just signing the message, not encrypting it. When Replying to the message it says the message size is 60KB.

I'm using Free-GPGMail Version 7.0 Build 200514.217
Mac Mail.app Version 16.0
Mail Server is Exchange 2013

**Comment by PhilETaylor** [comment]
Known issue "at the other place"... I reported it and it was already fixed in the nightlies of that app.

**Comment by PhilETaylor** [comment]
Do you have a S/MIME certificate as well as using GPG ?

**Comment by jameswillhoite** [comment]
> Known issue "at the other place"

Other place being? Exchange?



> Do you have a S/MIME certificate as well as using GPG ?

No just GPG

**Comment by PhilETaylor** [comment]
> Other place being? Exchange?

http://gpgtools.tenderapp.com/

<img width="691" alt="ScreenShot-2023-01-27-19 02 22" src="https://user-images.githubusercontent.com/400092/215173673-a7485175-1d8f-4597-a4aa-61f094b6cf95.png">

**Comment by jameswillhoite** [comment]
How can I get that nightlies? When following that link I get a 404 Not Found. Also tried checking the "Beta" releases in settings, but says I'm up to date.

**Comment by bnavigator** [comment]
https://releases.gpgtools.org/nightlies/

If you want support from GPGTools, you must buy their product, however.

**Comment by jameswillhoite** [comment]
Thank you very much.

**Comment by jameswillhoite** [comment]
Just a FYI, I thought this fixed the issue, and for the most of it, it has, but I did just now run into the same issue. This time a little different. I went into my Sent folder and replied/forwarded it to someone else. This caused the same issue. But this has been the first time since I updated to the Nightly. I know this is a GPGSuite issue and not the Free-GPGMail, but wanted to update this issue.

**Comment by tucnak** [comment]
They have just released an update that apparently resolves the issue. @bnavigator is GPG Suite actually open source, and if it is then where do you get it? The readme is unclear on that, and neither is the https://gpgtools.org/ homepage.

**Comment by austinhuang0131** [comment]
@tucnak They usually wait 30 days or so before posting the source code. When it appears, it'll be next to the 3 links under the download button.

**Comment by PhilETaylor** [comment]
To be clear, the current version (28th Feb) from GPGTools.org, and the nightly (27th Feb), still do not work (UUID changes) on the very latest Beta of `MacOS 13.3 Beta 2 (22E5230e)` but the SMIME bug with saving drafts was fixed and worked right up until upgrading to `MacOS 13.3 Beta 2 (22E5230e)` (It worked in Beta 1)

**Comment by jameswillhoite** [comment]
I am not on Beta and I have updated with the nightly (27th Feb) and I still have the same issue with PGP. I do not use SMIME. I have not done the actual GPGTools upgrade, just the nightly.

**Comment by jameswillhoite** [comment]
> To be clear, the current version (28th Feb) from GPGTools.org, and the nightly (27th Feb), still do not work (UUID changes) on the very latest Beta of `MacOS 13.3 Beta 2 (22E5230e)` but the SMIME bug with saving drafts was fixed and worked right up until upgrading to `MacOS 13.3 Beta 2 (22E5230e)` (It worked in Beta 1)

So does that mean just the issues with SMIME have been fixed and even with the new GPGTools the GPG drafts are still a bug?

**Comment by PhilETaylor** [comment]
https://gpgtools.org/releases/gpgsuite/release-notes.html

The issue with SMIME and drafts is fixed in the Feb 28th release of Official GPGMail.
The other issue with saving in drafts is fixed in the Feb 28th release of Official GPGMail.

> Fixes a problem where saving a draft or sending a reply to an encrypted or signed message was not possible when replying the successful activation dialog would be shown on every Mail launch in case automatic support plan activation was configured [#1135]


> Draft saving and sending error on macOS 13.2
> Under specific circumstances, saving a draft or sending a reply to an encrypted or sign message failed with an error that attachments are too large or that the message could not bet sent

**Neither are yet fixed in Free-GPGMail as the source code has not yet been released.**

**Comment by jameswillhoite** [comment]
Thanks, was a little confused if it was the issue with SMIME that was fixed, or if both were fixed.

**Comment by AwlsomeAlex** [comment]
Source is out.
