### ISSUE TITLE
S/MIME and default

### ISSUE THREAD

**Issue by matteocorti** [Free-GPGMail/Free-GPGMail#76]
Is there a way to set the default signing method? With the plugin emails are automatically signed with GPG but I would like to set S/MIME as default.

**Comment by kyvandoan** [comment]
S/MIME as default can be achieved with this: 
`defaults write org.free-gpgmail.gpgmail DefaultSecurityMethod -int 1|2`

Reference: [[](https://github.com/Free-GPGMail/Free-GPGMail/issues/16#issuecomment-1002211541)](https://github.com/Free-GPGMail/Free-GPGMail/issues/16#issuecomment-1002211541)

**Comment by bnavigator** [comment]
Thanks @kyvandoan
