### ISSUE TITLE
Incompatible Plug-ins Disabled

### ISSUE THREAD

**Issue by Flojan** [Free-GPGMail/Free-GPGMail#82]
Hello, 

on Ventura 13.3 I always receive the following error message if I enable the plugin and restart the Mail app: 

![Screenshot 2023-04-04 at 08 54 21](https://user-images.githubusercontent.com/33030019/229713004-87208610-7645-47c0-98ce-b080cfd30390.png)

`sw_vers -productVersion` 
=> 13.3
`defaults read /System/Applications/Mail.app/Contents/Info PluginCompatibilityUUID` 
=> 281F8A5C-0AF9-4BE6-8B8A-C0CB9C2068BE

I have already checked out if this UUID exists in info.plist.

Thanks in advance!

**Comment by bnavigator** [comment]
> I have already checked out if this UUID exists in info.plist.

And what is the result of your check? Because it should be present and the error message should not appear.

https://github.com/Free-GPGMail/Free-GPGMail/blob/d4b0446c9250941ecffba515759b20503b094ee0/Source/GPGMail_7/Resources/Info.plist#L54

Are you sure you have installed Free-GPGMail_7.mailbundlde from the 2023.1 release? Your Info.plist should also contain these lines:

```xml
	<key>BuildMachineOSBuild</key>
	<string>21G419</string>
	<key>BuildNumber</key>
	<string>203492</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleDocumentTypes</key>
	<array/>
	<key>CFBundleExecutable</key>
	<string>Free-GPGMail</string>
	<key>CFBundleIconFile</key>
	<string>GPGMail.icns</string>
	<key>CFBundleIdentifier</key>
	<string>org.free-gpgmail.gpgmail7</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>Free-GPGMail</string>
	<key>CFBundlePackageType</key>
	<string>GpgM</string>
	<key>CFBundleShortVersionString</key>
	<string>7.1</string>
```

**Comment by Flojan** [comment]
The result is that the UUID exists, I just checked that here on GitHub in the info.plist file which you linked.
And yes, I installed the latest version of Free-GPGMail using Homebrew:

![image](https://user-images.githubusercontent.com/33030019/229728241-7d00c0c1-4b58-4c35-9529-5129a60855d1.png)

**Comment by bnavigator** [comment]
You have to check it in your installed mailbundle, not in the source. Also, make sure that you only have one mailbundle installed in the various `*/Library/*` places so that the correct one is loaded. Homebrews' installation scheme is not flawless (see #81).

**Comment by Flojan** [comment]
Ok, I checked the info.plist in my installed mailbundle and it contains all the required lines. But I found the mailbundle two times in various places in the `/Library`. I deleted the wrong one and now it works. Thanks for your help!
