### ISSUE TITLE
No recipient specified!

### ISSUE THREAD

**Issue by jaimefeldman** [Free-GPGMail/Free-GPGMail#83]
when open mail say Error: No recipient specified! alert message

**Comment by bnavigator** [comment]
Need more info. Versions, Installmethod, etc.

**Comment by andrewmolyuk** [comment]
The same issue.
Installed by `brew install --cask free-gpgmail`
Version free-gpgmail: 7.1,2023.1
MacOS Ventura 13.4 (22F66)
MacBook Pro 16-inch, 2021, 32 GB RAM
<img width="262" alt="Screenshot 2023-06-14 at 19 36 20" src="https://github.com/Free-GPGMail/Free-GPGMail/assets/3962313/e6ada062-9f0f-467f-b73c-8734ed48973a">

Solved by adding my gpg key to the GPG Keychain.

**Comment by bnavigator** [comment]
Thanks, looks like using Free-GPGMail without a key is pointless.
