### ISSUE TITLE
Question on Sonoma support

### ISSUE THREAD

**Issue by fclaerho** [Free-GPGMail/Free-GPGMail#86]
MacOS 14 Sonoma will drop support for legacy plugins, and it seems this will impacts Free-GPGMail, if I'm not mistaken.

Is there any plan to port this into the Mail.app extension framework?

Many thanks in advance.

**Comment by bnavigator** [comment]
This is only a liberation fork of GPG Mail from the GPG Suite. I don't know if GPG Tools works on updating their product to the new framework. If they do, the next question will be if the updated plugin will still be based on the existing code and thus will be published as open source. Only if that is the case, then we can provide a free version without a subscription plan.

Alternatively someone else will have to come up with a free implementation of GPG for Mail.app.

**Comment by fclaerho** [comment]
Understood, thanks for the reply!

**Comment by thomasdeniau** [comment]
It looks like this can be implemented using https://developer.apple.com/documentation/mailkit/memessagesecurityhandler

**Comment by c-harding** [comment]
GPG Tools has published an article about Mail Extensions: https://gpgtools.org/sonoma

**Comment by bnavigator** [comment]
See #100 for recent developments

**Comment by decorte** [comment]
they have a working public beta now #100
