### ISSUE TITLE
Free-GPGMail 7 is not compatible with macOS Ventura >= 13.5 

### ISSUE THREAD

**Issue by naga-re** [Free-GPGMail/Free-GPGMail#88]
For information, the new version of macOS Ventura 13.5 and mail.app 16.0 (3731.700.6) broke the compatibility of the plugin due to a new method.

GPGTools has just released an update with these changes:

> Adapts GPG Mail 7 to changes of Mail in macOS 13.5
> A method of macOS Mail that was previously used by GPG Mail to create outgoing messages has been removed and replaced by a new one
> GPG Mail 7.2 addresses that change and calls the new method if available
> GPG Mail 7.2 (macOS Ventura)
> 
> Fixes
> Fixes a problem where macOS Mail would crash as GPG Mail is calling a method that no longer exists in Mail for macOS 13.5 [#1148]
> Makes sure to suppress macOS Mail's "public key not available"-dialog when the user is trying to reply to an encrypted message in plain, as GPG Mail's warning is already shown [#1144]

We just have to wait then…

**Comment by rafaelmaeuer** [comment]
Glad to find this issue, as mail is unexpectedly crashing at the moment...

**Comment by mbajor** [comment]
@bnavigator I see that the sources have already been released. When can we expect the build?
Thanks in advance.

**Comment by bnavigator** [comment]
I'm currently on travel. I'm only back at my workstation and have some free time by the end of the month. 

But if someone want's to open a PR, I might have the resources to have a look:

1. Update the `unchanged-source` branch with the new sources
2. create a new feature branch from `master` and merge  `unchanged-source` into it
3. Resolve merge conflicts, update liberation from support plan, if necessary
4. Create PR

**Comment by bnavigator** [comment]
Unfortunatly the notarization of the compiled mailbundles failed. I will have to investigate as soon as I have some time for it. (My Apple Developer Account might have run into some timeout. Ironically I a currently only a few miles from the Apple Headquarters)

Here is the unsigned mailbundle:
[Free-GPGMail_7.mailbundle.zip](https://github.com/Free-GPGMail/Free-GPGMail/files/12308913/Free-GPGMail_7.mailbundle.zip)

**Comment by bnavigator** [comment]
I was able to log in and refresh the license agreement. Notarization completed, 2023.3 is released
