### ISSUE TITLE
Support for 2020.2?

### ISSUE THREAD

**Issue by cgtyoder** [Free-GPGMail/Free-GPGMail#9]
Has any testing been done with the new 2020.2 release? Can I upgrade and then make changes as for 2020.1? (Currently running Catalina macOS 10.15.7)

**Comment by bnavigator** [comment]
Not that I am aware of. #5 and #7 mention problems with Big Sur only. Could you please test and report back?

**Comment by sT331h0rs3** [comment]
Source code has been published by GPG Suite: https://releases.gpgtools.org/GPG_Suite-2020.2.txz

**Comment by bnavigator** [comment]
#10
