### ISSUE TITLE
crashes mail version 16.0 (3731.700.6)

### ISSUE THREAD

**Issue by morriswinkler** [Free-GPGMail/Free-GPGMail#94]
I just updated my OSX yesterday and drafting/sending mail crashed.

After disabling `Encrypt drafts` and `Sign new emails` the mail program worked again.

I guess the internal mail API might have had some changes. 

OSX version: 13.5 (22G74)
Mail version: 16.0 (3731.700.6)

**Comment by damianmarzec** [comment]
Same here.
OSx : 13.5.1 (22G90)
Mail: Version 16.0 (3731.700.6)

**Comment by bnavigator** [comment]
Please make sure that you really have Free-GPG Mail 7.2 and not some old version (See e.g. https://github.com/Free-GPGMail/Free-GPGMail/issues/82#issuecomment-1495572660 that this can happen unintentionally)

**Comment by morriswinkler** [comment]
@bnavigator you are right, but it was not that easy to update here are the steps that worked for me

First open [ OSX -> System Settings -> Privacy & Security -> Full Disk Access ] and add/enable your terminal program
Then:
```
brew update 
brew uninstall free-gpgmail
brew install free-gpgmail
```
And finally:
Open Mail -> Settings -> General on the bottom right click Manage Plug-ins  and enable Free-GPGMail_7

**Comment by bnavigator** [comment]
Looks like the wrong mailbundle was active
