### ISSUE TITLE
No recipient specified! Not able to write E-Mail

### ISSUE THREAD

**Issue by Lennolium** [Free-GPGMail/Free-GPGMail#99]
Hello,

Whenever I'm writing an E-Mail I get after a few seconds following error message:

> Deine Nachricht konnte aufgrund eines unbekannten Fehlers nicht verschlüsselt werden
> Unglücklicherweise kann Free-GPGMail den Fehler an dieser Stelle nicht behandeln.
> 
> Sollte dein Problem fortbestehen, kontaktiere uns bitte auf https://github.com/Free-GPGMail/Free-GPGMail/issues und teilen uns folgende Fehlerbeschreibung mit:
> 
> No recipient specified!

I can click the error message away, but after a few seconds of continued writing I get the message again.
I already tried to uninstall and reinstall Free-GPGMail, but the error still occurs.

Thanks!
Lennart

**Comment by Lennolium** [comment]
Checking back: my issue is related to apple's new mail plugin architecture. So this can be closed.

**Comment by gregorvolkmann** [comment]
How did you solve this? You were forced to upgrade macOS?

**Comment by Lennolium** [comment]
I could not fix it. Its Apple changing the mail extension system. So either wait until freegpg adapts their code or use the [paid](https://gpgtools.com/support-plan) (beta) version, which had updates regarding that.
